import {
  Apple,
  Baby,
  Banana,
  Beef,
  Beer,
  Bike,
  BookOpen,
  Briefcase,
  Candy,
  Car,
  Carrot,
  Cherry,
  Citrus,
  Coffee,
  CreditCard,
  Cookie,
  Croissant,
  CupSoda,
  Drumstick,
  Droplet,
  Egg,
  Ellipsis,
  Fish,
  Gamepad2,
  GlassWater,
  Gift,
  Grape,
  Ham,
  HeartPulse,
  Home,
  IceCreamCone,
  type LucideIcon,
  Milk,
  Music,
  PawPrint,
  Pizza,
  Plane,
  Popcorn,
  Salad,
  Sandwich,
  Shirt,
  ShoppingCart,
  Soup,
  Star,
  Utensils,
  Wheat,
  Wine,
  Wrench,
} from 'lucide-react-native';

const iconMap: Record<string, LucideIcon> = {
  'shopping-cart': ShoppingCart,
  cookie: Cookie,
  'cup-soda': CupSoda,
  coffee: Coffee,
  utensils: Utensils,
  bike: Bike,
  car: Car,
  home: Home,
  droplet: Droplet,
  shirt: Shirt,
  'credit-card': CreditCard,
  'gamepad-2': Gamepad2,
  'heart-pulse': HeartPulse,
  'paw-print': PawPrint,
  ellipsis: Ellipsis,
  baby: Baby,
  'book-open': BookOpen,
  briefcase: Briefcase,
  gift: Gift,
  music: Music,
  plane: Plane,
  star: Star,
  wrench: Wrench,
  milk: Milk,
  egg: Egg,
  croissant: Croissant,
  wheat: Wheat,
  drumstick: Drumstick,
  ham: Ham,
  beef: Beef,
  fish: Fish,
  apple: Apple,
  banana: Banana,
  citrus: Citrus,
  grape: Grape,
  cherry: Cherry,
  salad: Salad,
  carrot: Carrot,
  candy: Candy,
  popcorn: Popcorn,
  pizza: Pizza,
  sandwich: Sandwich,
  soup: Soup,
  'ice-cream-cone': IceCreamCone,
  'glass-water': GlassWater,
  wine: Wine,
  beer: Beer,
};

export const SELECTABLE_ICON_NAMES = Object.keys(iconMap);

export function getCategoryIcon(iconName: string): LucideIcon {
  return iconMap[iconName] ?? Ellipsis;
}
